<h1> Python Basics</h1> 

<br/>

<p>
This tutorial introduces some important aspects of the Python programming language. For more comprehensive introductions and a complete reference, the following links may be useful:

- [The Python Tutorial](https://docs.python.org/3/tutorial/index.html) introduces the reader informally to the basic concepts and features of the Python language and system.    
- The [Scipy Lecture Notes](https://scipy-lectures.org/) is a tutorial on the scientific Python ecosystem including libraries such as Numpy, Scipy, and Matploblib.   
- The Python package [LibROSA](https://librosa.github.io/) provides many building blocks to create music information retrieval systems. It also cotains a [gallery](https://librosa.github.io/librosa/advanced.html) of more advanced examples. 
</p>

## Data Types

Let us start with some basic facts on Python variables:
- Variables do not need to be declared; neither their type.
- Variables are created automatically when they are first assigned.
- A variable name may contain letters (`a`, `b`, ..., `Y`, `Z`) and the underscore (`_`).
- Variable names are **case sensitive**.
- All but the first character can also be positive integer number.
- Usually one uses lower case letters and underscores to separate words.


### Strings
A string is given in single ticks (`'`) or double ticks (`"`). If there is no other reason, we recommend single ticks. Let's assign a string to a variable and print it using the `print`-command.

In [1]:
string_variable="welcome"
print(string_variable)

welcome


Here some basic string formatting:

In [3]:
print("this is an example {}".format(string_variable))
print("this is an integer {:d}".format(17))
print("this is a string: {:s} and this is string2:{:,3}".format('ABCD'))
print("this is a floating point number: {:06}")

this is an example welcome
this is an integer 17


IndexError: Replacement index 1 out of range for positional args tuple

### Basic math

In [5]:
n=3
print(n+1)
print(n-1)
print(n*2)
print(n/2)
print(n//2)
print(n**2)

4
2
6
1.5
1
9


Division always results in a floating point number, even if the number is divisible without remainder. (Note that there are differences between **Python 2** and **Python 3** in using `/`). If the result should be an integer (e.g. when using it as an index), one may use the `//` operator. The `%` yields the remainder.

In [ ]:
n=8
print(n/2)
print(n//2)

For re-assigning a variable, one may use the following conventions:

In [6]:
n=7
n+=11
print(n)

18


### List and tuples

The basic compound data types in Python are **lists** and **tuples**. A list is enclosed in square brackets and a tuple is enclosed in round brackets. Both are indexed with square brackets (with indexing starting with $0$). The `len` function gives the length of a tuple or a list.

In [9]:
var_lis=['I','am','a','list']
var_tup=('I','am','a','tuple')
print(var_lis)
print(var_tup)

print(var_lis[0])
print(len(var_lis))

print(type(var_lis))
print(type(var_tup))

['I', 'am', 'a', 'list']
('I', 'am', 'a', 'tuple')
I
4
<class 'list'>
<class 'tuple'>


What is the difference between a list and a tuple? Tuples are **immutable** objects (i.e., their state cannot be modified after they are created) and a bit more efficient. Lists are more flexible. Here are some examples for list operations:

In [11]:
var_lis=[1,2,3]
print(var_lis)
var_lis[0]=-1
print(var_lis)
var_lis.append(10)
print(var_lis)

var_lis=var_lis + ['a','12',[13,14]]
print(var_lis)

[1, 2, 3]
[-1, 2, 3]
[-1, 2, 3, 10]
[-1, 2, 3, 10, 'a', '12', [13, 14]]


One can index a list with start, stop, and step values (`[start:end:step`). Note that, in Python, the last index value is `end-1`. Negative indices are possible with `-1` referring to the last index. When not specified, `start` refers to the first item, `end`  to the last item, and `step` is set to $1$.

In [13]:
var_lis=[11,12,13,14,15]
print(var_lis[0:3])
print(var_lis[1:3])
print(var_lis[:3])
print(var_lis[-2])
print(var_lis[0:4:2])
print(var_lis[::-1])

[11, 12, 13]
[12, 13]
[11, 12, 13]
14
[11, 13]
[15, 14, 13, 12, 11]


The following examples shows how the elements of a list or tuple can be assigned to variables (called **unpacking**):

In [15]:
var_lis=[1,2]
[a,b]=var_lis
print(b)

var_tup=(3,4)
[a,b]=var_tup
print(a)

2
3


Leaving out brackets, tuples are generated.

In [16]:
a,b =var_lis
print(a)

1


The `range`-function can be used to specify a tuple or list of integers (without actually generating these numbers):

In [17]:
print(range(9))
print(range(0,9,2))

range(0, 9)
range(0, 9, 2)


A range can then be converted into a tuple or list as follows:

In [18]:
list(range(9))

[0, 1, 2, 3, 4, 5, 6, 7, 8]

List comprehensions provide a concise way to create lists. 


In [21]:
nums=[0,1,2,3,4]
squared=[x**2 for x in nums if x%2==0]
print(squared)

[0, 4, 16]


### Boolean

Boolean values in Python are `True` and `False`. Here are some examples for basic comparisons:

In [22]:
a=1
b=2
print(a<b)
print(a<=b)
print(a==b)
print(a!=b)

True
True
False
True


The `bool` function converts an arbitrary value into a boolean value. Here, are some examples:

In [24]:
print(bool('a'))
print(bool(''))
print(bool(1))
print(bool(0))
print(bool([]))

True
False
True
False
False


### Sets and dictionaries

In [28]:
s = {4,1,2,2}
print(s)
print({1,2,3}|{2,3,4})

d={'a':1,'b':2,3:'hello'}
print(d)
print(d[3])
print(d.keys())
print(d.values())

{1, 2, 4}
{1, 2, 3, 4}
{'a': 1, 'b': 2, 3: 'hello'}
hello
dict_keys(['a', 'b', 3])
dict_values([1, 2, 'hello'])


## Basic Control Structures

For control structures such as `if`, `for` or `while` one has to use indentations (as part of the syntax). A typical Python convention is to use four spaces. For example, an `if`-statement is written as follows:

In [ ]:
n=2
if n==2:
    print('True')
else:
    print('False')

The next example shows how to use a `for`-loop. Note that an iterable may be specified by a range, a list, a tuple, or even other structures.

In [29]:
for i in range[3]:
    print(2)

TypeError: 'type' object is not subscriptable

A `while`-loop is written as follows:

In [30]:
a=0
while a<5:
    print(a)
    a+=1

0
1
2
3
4


## Functions

One defines functions with the `def`-keyword. As variable names, function names may contain letters (`a`, `b`, ..., `Y`, `Z`) and the underscore (`_`). All but the first character can also be positive integer number. Usually one uses lower case letters and underscores to separate words.

The following function is named `add`. It has three arguments `a`, `b`, and `c` (with `b` and `c` having a default value). The `return` keyword is succeeded by the return value.

In [32]:
def add(a,b,c):
    return a+b+c

print(add(5,6,1))
print(add(10))
print(add(a=1,b=3,c=6))
print(add(1,3,6))


12


TypeError: add() missing 2 required positional arguments: 'b' and 'c'

There can also be multiple return values (which are returned as a tuple):

In [33]:
def add_and_diff(a,b=0):
    return a+b,a-b

add_res,sub_res=add_and_diff(3,5)
print(x)
print(add_res)
print(sub_res)

NameError: name 'x' is not defined

## Classes

The definition of classes in Python is quite straightforward:

In [36]:
class Greeter:
    
    def __init__(self,name):
        self.name=name
    
    def greet(self, loud=False):
        if loud:
            print("HELLO {}!".format(self.name.upper()))
        else:
             print("HELLO {}!".format(self.name))

In [37]:
g = Greeter(name="Fred")
g.greet(loud=False)
g.greet(loud=True)

HELLO Fred!
HELLO FRED!


## NumPy

Python has several useful built-in packages as well as additional external packages. One such package is **NumPy**, which adds support for multi-dimensional arrays and matrices, along with a number of mathematical functions to operate on these structures, see [NumPy Reference Manual](https://docs.scipy.org/doc/numpy/reference/) for details. In the following, we give some examples.

The NumPy package is imported as follows:

In [40]:
import numpy as np

It is convenient to bind a package to a short name (for example `np` as above). This short name appears as prefix when calling a function from the package. This is illustrated by the following `array`-function provided by numpy:

In [41]:
x=np.array([1,2,3,4])
print(x)

[1 2 3 4]


Each array has a shape, a type, and a dimension. 

In [43]:
print(x.shape)
print(x.ndim)

(4,)
1


In this example, note that `x.shape` produces a one-element tuple, which is encoded by `(4,)` for disambiguation. (The object `(4)` would be an integer of type `int` rather than a tuple.)

Multi-dimensional arrays are created like follows:

In [45]:
x=np.array([[1,2,3],[4,5,6]])
print(x)
print(x.shape)
print(x.ndim)

[[1 2 3]
 [4 5 6]]
(2, 3)
2


There are a couple of functions for creating arrays:

In [47]:
print(np.zeros((2,3)))
print(np.ones((2,3)))
print(np.arange((2,20,4)))
print(np.random.rand((2,3)))
print(np.eye((3)))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


TypeError: arange: scalar arguments expected instead of a tuple.

Reshaping of an array is possible like follows:

In [ ]:
x=np.arange(2*3*4)
print(x)
print(x.shape)

y=x.reshape((3,8))
print(y)

y=x.reshape((3,8))
print(y)
y=x.reshape((3,8))
print(y)


NumPy allows for giving one of the new shape parameter as `-1`. In this case, NumPy automatically figures out the unknown dimension. Note that in the following example the difference between the shape `(6,)` and the shape `(6, 1)`.

In [49]:
x=np.arange(6)
print(x)

y=x.reshape((-1,1))
print(y)

[0 1 2 3 4 5]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


Numpy offers several ways to **index** into arrays.

* **Slicing** 

* **Integer array Indexing** 

* **Boolean array indexing** 



**Slicing**: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

You can also mix integer indexing with slice indexing. However, doing so will yield an array of lower rank than the original array. Note that this is quite different from the way that MATLAB handles array slicing:

**Integer array indexing**: When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array. In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array. Here is an example:

One useful trick with integer array indexing is selecting or mutating one element from each row of a matrix:



**Boolean array indexing**: Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition. Here is an example:

Basic **mathematical functions** operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:Applied to arrays, many operations are conducted in an element-wise fashion:

Note that unlike MATLAB, * is elementwise multiplication, not matrix multiplication. We instead use the `np.dot` function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. `np.dot` is available both as a function in the numpy module and as an instance method of array objects:

Note that arrays and lists may behave in a completely different way. For example, addition leads to the following results:

Numpy provides many useful functions for performing computations on arrays; one of the most useful is `np.sum`:



You can find the full list of mathematical functions provided by Numpy [in the documentation](https://numpy.org/doc/stable/reference/routines.math.html)

Apart from computing mathematical functions using arrays, we frequently need to reshape or otherwise manipulate data in arrays. The simplest example of this type of operation is transposing a matrix; to transpose a matrix, simply use the `T` attribute of an array object:

Specifying the **data type** for an array can be important in some situations.

**Broadcasting** is a powerful mechanism that allows Numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

For example, suppose that we want to add a constant vector to each row of a matrix. We could do it like this:

This works; however when the matrix `x` is very large, computing an explicit loop in Python could be slow. Note that adding the vector `v` to each row of the matrix `x` is equivalent to forming a matrix `vv` by stacking multiple copies of `v` vertically, then performing elementwise summation of `x` and `vv`. We could implement this approach like this:

Numpy broadcasting allows us to perform this computation without actually creating multiple copies of `v`. Consider this version, using broadcasting:

The line `y = x + v` works even though `x` has shape `(4, 3)` and `v` has shape `(3,)` due to broadcasting; this line works as if `v` actually had shape `(4, 3)`, where each row was a copy of `v`, and the sum was performed elementwise.

Broadcasting two arrays together follows these rules:

* If the arrays do not have the same number of dimensions, prepend (not append) the shape of the lower rank array with 1s until both shapes have the same length.

* The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.

* The arrays can be broadcast together if they are compatible in all dimensions.

* After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.

* In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension


Functions that support broadcasting are known as universal functions. You can find the list of all universal functions in the documentation.

Here are some applications of broadcasting:

## Matplotlib

You will need to install `matplotlib` library. You can do it using `conda install matplotlib` from your environment.

The library `matplotlib` is a widely used Python package for creating visualizations, allowing a user to produce high-quality figures in a variety of formats as well as interactive environments across platforms. The [main website](https://matplotlib.org/) contains a detailed documentation and links to illustrative code examples.  In particular, we recommend to have a look at the [gallery](https://matplotlib.org/gallery/index.html), which contains numerous examples of the many things you can do with `matplotlib`. In particular, we will use [`matplotlib.pyplot`](https://matplotlib.org/api/pyplot_api.html), which is a collection of command style functions that make matplotlib work similar to MATLAB. Following general conventions, we use the following abbreviation:

`import matplotlib.pyplot as plt`


We start with some basic examples that show how the library `matplotlib` works. First, we import various Python packages required in this notebook. The command `%matplotlib inline` ensures that the backend of `matplotlib` is set to `inline` so that figures are displayed within the Jupyter notebook. We then generate a sine and cosine function, which are plotted in the same figure. The axes are modified and labeled. Finally, the figure is exported in the `PNG` format.

The next example demonstrates how to create subplots using [`subplot` ](https://matplotlib.org/api/_as_gen/matplotlib.pyplot.subplot.html) and [`axes` ](https://matplotlib.org/api/_as_gen/matplotlib.pyplot.axes.html) as well as different features of `matplotlib`

Next, we illustrate how to visualize the graph of a function generated by Python. 

* We first generate a discrete-time signal $x$ using the sampling rate $F_\mathrm{s}=256$. 
* The we compute the discrete Fourier transform (DFT) $X$ of the signal by applying an FFT. 
* The complex-valued DFT $X$ is modified by setting all values which magnitudes are below a certain threshold $\tau$ to zero. This results in $X_\mathrm{mod}$.
* Finally, the inverse DFT is applied to reconstruct a time domain signal. We define $x_\mathrm{mod}$ to be the real part of this signal.